name: counterdartfrog
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
 bloc: ^8.1.0
 counter_repository:
    path: packages/counter_repository
 equatable: ^2.0.5
 flutter:
    sdk: flutter
 flutter_bloc: ^8.1.1
 flutter_localizations:
    sdk: flutter
 intl: ^0.17.0

dev_dependencies:

  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  bloc_test: ^9.1.0
  very_good_analysis: ^3.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true
